### ISSUE TITLE
Explore Result<T> from kotlin stdlib and use in library code if appropriate

### ISSUE THREAD

**Issue by skywall** [thefuntasty/mvvm-android#132]

**Comment by SumeraMartin** [comment]
Looks like that it won't be possible to use the kotlin Result class as a return value 

https://github.com/Kotlin/KEEP/blob/master/proposals/stdlib/result.md#limitations 

`The rationale behind these limitations is that future versions of Kotlin may expand and/or change semantics of functions that return Result type and null-safety operators may change their semantics when used on values of Result type. In order to avoid breaking existing code in the future releases of Kotlin and leave door open for those changes, the corresponding uses produce an error now. Exceptions to this rule are made for carefully-reviewed declarations in the standard library that are part of the Result type API itself.
`

It is possible to disable this compiler check by passing the following compilation argument `-Xallow-result-return-type` but I don't think that is something that we want to do.

I'm closing this issue.
